export enum OrcamentoEnum {
  DISPONIBILIZADO = 'DISPONIBILIZADO',

  REALIZADO = 'REALIZADO',

  PROPOSTA = 'PROPOSTA',

  SALDO = 'SALDO',

  TOTALAPROVADO = 'TOTALAPROVADO',

  PLANEJADAS = 'PLANEJADAS',
}
